/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { TestdriveService } from "../testdrive.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TestdriveCreateInput } from "./TestdriveCreateInput";
import { TestdriveWhereInput } from "./TestdriveWhereInput";
import { TestdriveWhereUniqueInput } from "./TestdriveWhereUniqueInput";
import { TestdriveFindManyArgs } from "./TestdriveFindManyArgs";
import { TestdriveUpdateInput } from "./TestdriveUpdateInput";
import { Testdrive } from "./Testdrive";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class TestdriveControllerBase {
  constructor(
    protected readonly service: TestdriveService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Testdrive })
  @nestAccessControl.UseRoles({
    resource: "Testdrive",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: TestdriveCreateInput,
  })
  async create(@common.Body() data: TestdriveCreateInput): Promise<Testdrive> {
    return await this.service.create({
      data: {
        ...data,

        owner: data.owner
          ? {
              connect: data.owner,
            }
          : undefined,
      },
      select: {
        attack_ran: true,
        attack_results: true,
        cleanup_ran: true,
        cleanup_results: true,
        createdAt: true,
        created_users: true,
        errors: true,
        id: true,
        name: true,
        notes: true,

        owner: {
          select: {
            id: true,
          },
        },

        prep_ran: true,
        prep_results: true,
        startTime: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Testdrive] })
  @ApiNestedQuery(TestdriveFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Testdrive",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<Testdrive[]> {
    const args = plainToClass(TestdriveFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        attack_ran: true,
        attack_results: true,
        cleanup_ran: true,
        cleanup_results: true,
        createdAt: true,
        created_users: true,
        errors: true,
        id: true,
        name: true,
        notes: true,

        owner: {
          select: {
            id: true,
          },
        },

        prep_ran: true,
        prep_results: true,
        startTime: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Testdrive })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Testdrive",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: TestdriveWhereUniqueInput
  ): Promise<Testdrive | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        attack_ran: true,
        attack_results: true,
        cleanup_ran: true,
        cleanup_results: true,
        createdAt: true,
        created_users: true,
        errors: true,
        id: true,
        name: true,
        notes: true,

        owner: {
          select: {
            id: true,
          },
        },

        prep_ran: true,
        prep_results: true,
        startTime: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Testdrive })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Testdrive",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: TestdriveUpdateInput,
  })
  async update(
    @common.Param() params: TestdriveWhereUniqueInput,
    @common.Body() data: TestdriveUpdateInput
  ): Promise<Testdrive | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          owner: data.owner
            ? {
                connect: data.owner,
              }
            : undefined,
        },
        select: {
          attack_ran: true,
          attack_results: true,
          cleanup_ran: true,
          cleanup_results: true,
          createdAt: true,
          created_users: true,
          errors: true,
          id: true,
          name: true,
          notes: true,

          owner: {
            select: {
              id: true,
            },
          },

          prep_ran: true,
          prep_results: true,
          startTime: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Testdrive })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Testdrive",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: TestdriveWhereUniqueInput
  ): Promise<Testdrive | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          attack_ran: true,
          attack_results: true,
          cleanup_ran: true,
          cleanup_results: true,
          createdAt: true,
          created_users: true,
          errors: true,
          id: true,
          name: true,
          notes: true,

          owner: {
            select: {
              id: true,
            },
          },

          prep_ran: true,
          prep_results: true,
          startTime: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
